import { listLazyRoutes } from '@angular/compiler/src/aot/lazy_routes';
import { Component } from '@angular/core';
import example from 'data/example.json';
import { Game } from 'src/app/lib/game.library';
import { Puzzle } from 'src/app/lib/interface.library';
import { parseGames, parseLichessGame } from 'src/app/lib/util.library';

@Component({
    selector: 'app-auto-generated-puzzles',
    templateUrl: './auto-generated-puzzles.component.html',
    styleUrls: ['./auto-generated-puzzles.component.css']
})
export class AutoGeneratedPuzzlesComponent {
    private _autoGeneratedPuzzles: Puzzle[];
    private games: any[];
    constructor() {
        this.autoGeneratedPuzzles = null;
        this.games = parseGames(example.example);
        // for (const puzzle of this.autoGeneratedPuzzles) {
        //     let node = puzzle.pgn.nextNodes[0];
        //     const game = new Game();
        //     while (
        //         node.nextNodes[0] &&
        //         node.nextNodes[0].move.charAt(
        //             node.nextNodes[0].move.length - 1
        //         ) !== '#'
        //     ) {
        //         // console.log('move', node.move);
        //         game.makeMove(node.move);

        //         // console.log(game.getLegalMoves());

        //         node = node.nextNodes[0];
        //     }
        //     if (
        //         !node.nextNodes[0] ||
        //         node.nextNodes[0].move.charAt(
        //             node.nextNodes[0].move.length - 1
        //         ) !== '#'
        //     ) {
        //         console.error(
        //             'our puzzle was supposed to lead to mate, ' +
        //                 "and for some reason, it didn't",
        //             puzzle
        //         );
        //     } else {
        //         puzzle.beginAt = node;
        //     }
        // }

        this.serveRandomPuzzle();

        // console.log('autoGeneratedpuzzles', this.autoGeneratedPuzzles);
    }

    serveRandomPuzzle() {
        let g = this.games[0];
        let puzzle = parseLichessGame(g);
        console.log('puzzle', puzzle);
    }

    get autoGeneratedPuzzles(): Puzzle[] {
        return this._autoGeneratedPuzzles;
    }
    set autoGeneratedPuzzles(puzzles: Puzzle[]) {
        this._autoGeneratedPuzzles = puzzles;
    }
}
