import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { PuzzlesComponent } from './components/puzzles/puzzles.component';
import { OpeningTrainingGameComponent } from './components/opening-training-game/opening-training-game.component';
import { AboutComponent } from './components/about/about.component';
import { EndgameTrainerComponent } from './components/endgame-trainer/endgame-trainer.component';
import { CoursesComponent } from './components/courses/courses.component';
import { AutoGeneratedPuzzlesComponent } from './components/puzzles/auto-generated-puzzles/auto-generated-puzzles.component';

const routes: Routes = [
    // {
    //     component: PuzzlesComponent,
    //     path: 'puzzles'
    // },
    {
        component: CoursesComponent,
        path: 'courses'
    },
    {
        component: AutoGeneratedPuzzlesComponent,
        path: 'auto-generated-puzzles'
    },
    // {
    //     component: EndgameTrainerComponent,
    //     path: 'endgame-trainer'
    // },
    // {
    //     component: OpeningTrainingGameComponent,
    //     path: 'opening-training-game'
    // },
    {
        component: AboutComponent,
        path: 'about'
    },
    {
        redirectTo: 'courses',
        path: '**'
    }
];

@NgModule({
    imports: [
        RouterModule.forRoot(routes, { relativeLinkResolution: 'legacy' })
    ],
    exports: [RouterModule]
})
export class AppRoutingModule {}
