import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { FooterComponent } from './components/footer/footer.component';
import { HeaderComponent } from './components/header/header.component';
import { GameComponent } from './components/game/game.component';
import { PuzzlesComponent } from './components/puzzles/puzzles.component';
import { GameDetailTableComponent } from './components/game-details-table/game-details-table.component';
import { OpeningTrainingGameComponent } from './components/opening-training-game/opening-training-game.component';
import { AboutComponent } from './components/about/about.component';
import { BoardOverlayComponent } from './components/board-overlay/board-overlay.component';
import { EndgameTrainerComponent } from './components/endgame-trainer/endgame-trainer.component';
import { CoursesComponent } from './components/courses/courses.component';
import { AutoGeneratedPuzzlesComponent } from './components/puzzles/auto-generated-puzzles/auto-generated-puzzles.component';
import { CommonModule } from '@angular/common';

@NgModule({
    declarations: [
        AppComponent,
        HeaderComponent,
        FooterComponent,
        GameComponent,
        GameDetailTableComponent,
        OpeningTrainingGameComponent,
        AboutComponent,
        BoardOverlayComponent,
        EndgameTrainerComponent,
        PuzzlesComponent,
        CoursesComponent,
        AutoGeneratedPuzzlesComponent
    ],
    imports: [CommonModule, BrowserModule, AppRoutingModule, FormsModule],
    providers: [],
    bootstrap: [AppComponent]
})
export class AppModule {}
